Description: Auto Scaling Group - with EC2 using existing network

Parameters:
  ExistingSubnetId:
    Type: AWS::EC2::Subnet::Id # give the id #
    Description: Subnet where EC2 instances will be launched

  ExistingSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id # give the id #
    Description: Security group for EC2 instances

Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyComputeLaunchTemplate # we can give it now, but if we use this code for re-deploy, it will show error : Launch template name already exists"
      LaunchTemplateData: # SO, better remove LaunchTemplateName to use this code for re-deploy#
        ImageId: ami-0f3caa1cf4417e51b
        InstanceType: t2.micro
        SecurityGroupIds:
          - !Ref ExistingSecurityGroup # Refers the existing netwok, so it won't create one on its own! #
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: ASG-EC2-Instance

  MyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref ExistingSubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
